version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always

  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    depends_on:
      - css
      - js
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/find_a_lost_trn_development
    ports:
      - 3000:3000

  js:
    build: .
    command: /bin/sh -c "yarn build --watch"

  css:
    build: .
    command: /bin/sh -c "yarn build:css --watch"
