version: '3.9'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    depends_on:
      - css
      - js
    ports:
      - 3000:80

  js:
    build: .
    command: /bin/sh -c "yarn build --watch"

  css:
    build: .
    command: /bin/sh -c "yarn build:css --watch"
