CONFIG=production_aks
DEPLOY_ENV=production
CONFIG_SHORT=pd
AZURE_SUBSCRIPTION=s189-teacher-services-cloud-production
AZURE_RESOURCE_PREFIX=s189p01
ENV_TAG=Prod
DOMAINS_TERRAFORM_BACKEND_KEY=faltrndomains_prod.tfstate