name: Docker build and push

inputs:
  github_username:
    description: GitHub Container Registry username
    required: true
  github_token:
    description: GitHub Container Registry token
    required: true

outputs:
  docker_image_tag:
    description: Docker Container tag
    value: ${{ steps.image.outputs.tag }}

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker image tag
      id: image
      run: |
        echo ::set-output name=tag::$CONTAINER_REGISTRY/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):$GITHUB_SHA
      env:
        CONTAINER_REGISTRY: ghcr.io
      shell: bash

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.github_username }}
        password: ${{ inputs.github_token }}

    - name: Docker build & push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.image.outputs.tag }}
