performance_alert:
  cron: "0 9 * * MON"
  class: "PerformanceAlertJob"

zendesk_health_alert:
  cron: "0 10 * * *"
  class: "ZendeskHealthJob"

trn_request_monthly:
  cron: "0 12 1 * *"
  class: "TrnRequestExportJob"
