performance_alert:
  cron: "0 9 * * MON"
  class: "PerformanceAlertJob"

zendesk_health_alert:
  cron: "0 10 * * *"
  class: "ZendeskHealthJob"

zendesk_delete:
  cron: "0 11 * * *"
  class: "ScheduleZendeskTicketsForDeletionJob"

zendesk_delete_alert:
  cron: "0 11 * * TUE"
  class: "DeleteZendeskTicketsAlertJob"
