name: Build No Cache

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * 0"
    # Will run once a week on Sunday afternoon

permissions:
  packages: write
  contents: write
  pull-requests: write
  id-token: write

jobs:
  build-no-cache:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@v6
        name: Checkout

      - name: Build without cache and push docker image
        id: build-image
        uses: DFE-Digital/github-actions/build-docker-image@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          context: .
          max-cache: true
          reuse-cache: false
          snyk-token: ${{ secrets.SNYK_TOKEN }}

      - name: Notify teams channel failure
        if: ${{ failure() }}
        uses: DFE-Digital/github-actions/send-to-teams-channel@master
        with:
          teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: Build failure
          service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
          message: |
            Rebuild docker cache failure
