name: Deploy

on:
  push:
    branches:
      - 708_replicate_prod_to_aks

  pull_request:
    branches:
      - main
    types:
      - labeled
      - synchronize
      - reopened
      - opened
      - converted_to_draft

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  docker:
    name: Docker build and push
    if: contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'deploy_v2') || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      docker_image: ${{ steps.dockerimage.outputs.docker_image_tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/build-docker
        id: dockerimage
        with:
          github_username: ${{ github.actor }}
          github_token: ${{ secrets.GITHUB_TOKEN }}


  deploy_v2_production:
    name: Deploy to production_aks environment
    runs-on: ubuntu-latest
    continue-on-error: true
    environment:
      name: production_aks
    concurrency: deploy_production_aks
    needs: [docker]

    outputs:
      environment_url: ${{ steps.deploy_v2.outputs.environment_url }}

    steps:
      - uses: actions/checkout@v3
      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: ./.github/workflows/actions/deploy_v2
        id: deploy_v2
        with:
          environment: production_aks
          docker_image: ${{ needs.docker.outputs.docker_image }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          arm-access-key: ${{ secrets.ARM_ACCESS_KEY }}
