name: Manual deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy environment ( development, test, preprod or production )"
        required: true
        default: development
        type: choice
        options:
          - development
      sha:
        description: Commit sha to be deployed
        required: true
        default: 588bfd4567e53f6b809d5ed107dc70b3d040710a
        type: string
env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  deploy_environment:
    name: Deploy to development environment
    runs-on: ubuntu-latest
    environment:
      name: development
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Docker image tag
        id: image
        run: |
          echo ::set-output name=tag::$CONTAINER_REGISTRY/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):$INPUT_GITHUB_SHA
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          INPUT_GITHUB_SHA: ${{ inputs.sha }}
        shell: bash

      - uses: ./.github/workflows/actions/deploy
        id: deploy
        with:
          environment: development
          docker_image: ${{ steps.image.outputs.tag }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          arm-access-key: ${{ secrets.ARM_ACCESS_KEY }}

      - uses: ./.github/workflows/actions/smoke-test
        id: smoke-test
        with:
          environment: development
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
