name: Manual deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy environment ( dev, test, preprod or production )"
        required: true
        default: dev
        type: environment
        options:
          - dev
          - test
          - preprod
          - production
      sha:
        description: Commit sha to be deployed
        required: true
env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  deploy_environment:
    name: Deploy to ${{ github.event.inputs.environment }} environment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Docker image tag
        id: image
        run: |
          echo ::set-output name=tag::$CONTAINER_REGISTRY/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):$INPUT_GITHUB_SHA
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          INPUT_GITHUB_SHA: ${{ inputs.sha }}
        shell: bash

      - uses: ./.github/workflows/actions/deploy-environment
        id: deploy
        with:
          environment_name: ${{ github.event.inputs.environment }}
          docker_image: ${{ steps.image.outputs.tag }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          terraform_vars: workspace_variables/${{ github.event.inputs.environment }}.tfvars.json
