name: Lint

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env
        with:
          skip-node: true

      - name: Run Prettier
        run: bin/bundle exec rbprettier --check --ignore-unknown --loglevel warn '**/*'

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env
        with:
          skip-node: true

      - name: Run Rubocop
        run: bin/bundle exec rubocop
