name: Lint

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env

      - name: Run Prettier
        run: yarn prettier --check --ignore-unknown --log-level warn '**/*'

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env

      - name: Run Rubocop
        run: bin/bundle exec rubocop

  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # Pinned at v4.0.1
        with:
          terraform_version: 1.14.5

      - name: Check formatting
        run: terraform fmt -check -recursive
        working-directory: terraform

      - name: Download vendor modules
        run: make ci development vendor-modules

      - name: Validate
        run: |
          terraform init -backend=false
          terraform validate -no-color
        working-directory: terraform/aks
