name: Lint

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env

      - name: Run Prettier
        run: yarn prettier --check --ignore-unknown --log-level warn '**/*'

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env

      - name: Run Rubocop
        run: bin/bundle exec rubocop

  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # Pinned at v3.1.2
        with:
          terraform_version: 1.5.0

      - name: Check formatting
        run: terraform fmt -check -recursive
        working-directory: terraform

      - name: Download vendor modules
        run: make ci development vendor-modules

      - name: Validate
        run: |
          terraform init -backend=false
          terraform validate -no-color
        working-directory: terraform/aks
