name: Lint

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  ruby-tests:
    name: Run linters
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env

      - name: Run Prettier
        run: bundle exec rbprettier --check --ignore-unknown --loglevel warn '**/*'

      - name: Run Rubocop
        run: bundle exec rubocop
