name: Test

on:
  push:
    branches:
      - '**'

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  rspec:
    name: Build & Test
    runs-on: ubuntu-20.04
    outputs:
      docker_image: ${{ steps.image.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env

      - name: Build frontend
        run: yarn build && yarn build:css

      - name: Run tests
        run: bundle exec rspec --format documentation

      - name: Docker image tag
        id: image
        run: |
          echo ::set-output name=tag::$CONTAINER_REGISTRY/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):$GITHUB_SHA

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.image.outputs.tag }}
