name: Test

on:
  push:
    branches:
      - '**'

jobs:
  rspec:
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/find_a_lost_trn_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env

      - name: Build frontend
        run: yarn build && yarn build:css

      - name: Setup DB
        run: bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rspec --format documentation
